//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LostItem
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public int ownerid { get; set; }
        public string status { get; set; }
        public int departmentid { get; set; }
        public Nullable<System.DateTime> lostdate { get; set; }
    }
}
